# Generated by Django 3.2.3 on 2021-05-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theevent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Event$', max_length=255),
        ),
    ]
